services:
    web:
        image: ghcr.io/finxol/karr-web:latest
        networks:
            - karr_network
        environment:
            - LOG_LEVEL=debug
        volumes:
            - /srv/http/karr/karr.config.yaml:/app/config/karr.config.yaml
        depends_on:
            - api

    api:
        image: ghcr.io/finxol/karr-api:latest
        networks:
            - karr_network
        secrets:
            - db-password
        environment:
            - DB_USER=karr
            - DB_HOST=db
            - DB_PASSWORD_FILE=/run/secrets/db-password
        volumes:
            - /srv/http/karr/karr.config.yaml:/app/config/karr.config.yaml
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        networks:
            - karr_network
        secrets:
            - db-password
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=karr
            - POSTGRES_DB=karr
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U karr"]
            interval: 5s
            timeout: 5s
            retries: 5

    caddy:
        image: ghcr.io/finxol/karr-caddy:latest
        networks:
            - karr_network
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        environment:
            - SITE_ADDRESS=karr.finxol.io
            - API_PORT=1993
            - WEB_PORT=3000
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:

networks:
    karr_network:

secrets:
    db-password: # needs a secret created with `printf "<password>" | docker secret create db-password -`
        external: true
