services:
    web:
        image: ghcr.io/finxol/karr-web:latest
        networks:
            - karr_network
        environment:
            - LOG_LEVEL=debug
        volumes:
            - /srv/http/karr/karr.config.yaml:/app/config/karr.config.yaml
        depends_on:
            - api

    api:
        image: ghcr.io/finxol/karr-api:latest
        networks:
            - karr_network
        secrets:
            - db-password
        environment:
            - DB_USER=karr
            - DB_HOST=db
            - DB_PASSWORD_FILE=/run/secrets/db-password
        ports:
            - 1993:1993
        volumes:
            - /srv/http/karr/karr.config.yaml:/app/config/karr.config.yaml
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        networks:
            - karr_network
        ports:
            - 5432:5432
        secrets:
            - db-password
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=karr
            - POSTGRES_DB=karr
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U karr"]
            interval: 5s
            timeout: 5s
            retries: 5

    caddy:
        image: ghcr.io/finxol/karr-caddy:latest
        networks:
            - karr_network
        ports:
            - "8088:8088"
        environment:
            - TZ=Europe/Paris
            - SITE_ADDRESS=http://karr2.finxol.io:8088
            - API_PORT=1993
            - WEB_PORT=3000
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:

networks:
    karr_network:

secrets:
    db-password: # needs a db-password.txt file created with `printf "<password>" > db-password.txt`
        file: ./pass.txt
