packages:
    - "apps/*"
    - "packages/*"
    - "tooling/*"
catalog:
    "@types/node": ^22.13.1
    "@types/react": 19.0.8
    "@types/react-dom": 19.0.3
    "confbox": ^0.1.8
    "tinyrainbow": ^2.0.0

    # Web packages
    "posthog-js": ^1.210.2
    "@tailwindcss/postcss": 4.0.0
    "tailwindcss": 4.0.0
    "babel-plugin-react-compiler": 19.0.0-beta-decd7b8-20250118
    "lucide-react": ^0.474.0
    "next": ^15.1.6
    "next-themes": ^0.4.4
    "react": ^19.0.0
    "react-dom": ^19.0.0
    "@tanstack/react-query": ^5.66.0
    "@hookform/resolvers": ^3.10.0
    "@radix-ui/react-separator": ^1.1.1
    "@radix-ui/react-slot": ^1.1.1
    "@radix-ui/react-label": ^2.1.1
    "@radix-ui/react-popover": ^1.1.4
    "date-fns": ^4.1.0
    "react-day-picker": ^9.5.0
    "react-hook-form": ^7.54.2
    "tailwind-merge": ^2.6.0
    "tailwindcss-animate": ^1.0.7
    "class-variance-authority": ^0.7.1
    "clsx": ^2.1.1
    "zod": ^3.24.1
    "ofetch": ^1.4.1

    # API packages
    "@hono/node-server": ^1.13.7
    "drizzle-kit": ^0.30.2
    "drizzle-orm": ^0.39.2
    "drizzle-zod": ^0.6.1
    "hono": ^4.6.17
    "postgres": ^3.4.5
    "esbuild": ^0.25.0

catalogs:
    tooling:
        "turbo": ^2.4.0
        "@turbo/gen": ^2.3.3
        "husky": ^9.1.7
        "@commitlint/cli": ^19.6.1
        "@commitlint/config-conventional": ^19.6.0
        "lint-staged": ^15.3.0
        "changelogen": ^0.5.7
        "prettier": ^3.4.2
        "@ianvs/prettier-plugin-sort-imports": ^4.4.0
        "prettier-plugin-tailwindcss": ^0.6.10
        "typescript": ^5.7.3
        "tsx": ^4.19.2
        "globals": ^15.12.0
        "typescript-eslint": ^8.15.0
        "@next/eslint-plugin-next": ^15.1.0
        "@tanstack/eslint-plugin-query": ^5.62.9
        "@typescript-eslint/eslint-plugin": ^8.15.0
        "@typescript-eslint/parser": ^8.15.0
        "eslint": ^9.19.0
        "@eslint/js": ^9.19.0
        "eslint-config-prettier": ^9.1.0
        "eslint-plugin-react": ^7.37.2
        "eslint-plugin-react-hooks": ^5.0.0
        "eslint-plugin-turbo": ^2.4.0

    vitest:
        "vitest": ^3.0.5
        "vite-tsconfig-paths": 5.1.4
