packages:
    - apps/*
    - packages/*
    - tooling/*

catalog:
    "@types/node": ^22.13.8
    "@types/react": 19.0.8
    "@types/react-dom": 19.0.3
    confbox: ^0.1.8
    tinyrainbow: ^2.0.0

    # Web packages
    "@hookform/resolvers": ^4.1.3
    "@radix-ui/react-separator": ^1.1.2
    "@radix-ui/react-slot": ^1.1.2
    "@radix-ui/react-label": ^2.1.2
    "@radix-ui/react-select": ^2.1.6
    "@radix-ui/react-popover": ^1.1.6
    "@tailwindcss/postcss": 4.0.0
    "@tanstack/react-query": ^5.66.0
    babel-plugin-react-compiler: 19.0.0-beta-decd7b8-20250118
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    framer-motion: ^12.4.7
    lucide-react: ^0.477.0
    next: ^15.2.0
    next-themes: ^0.4.4
    next-intl: ^3.26.3
    ofetch: ^1.4.1
    posthog-js: ^1.218.2
    react: ^19.0.0
    react-dom: ^19.0.0
    react-day-picker: ^9.5.0
    react-hook-form: ^7.54.2
    tailwindcss: 4.0.0
    tailwindcss-animate: ^1.0.7
    sonner: ^2.0.1
    tailwind-merge: ^3.0.2
    zod: ^3.24.1

    # API packages
    "@hono/node-server": ^1.13.7
    drizzle-kit: ^0.30.2
    drizzle-orm: ^0.40.0
    drizzle-zod: ^0.6.1
    esbuild: ^0.25.0
    hono: ^4.7.2
    postgres: ^3.4.5

catalogs:
    tooling:
        "@commitlint/cli": ^19.6.1
        "@commitlint/config-conventional": ^19.6.0
        "@eslint/js": ^9.21.0
        "@ianvs/prettier-plugin-sort-imports": ^4.4.0
        "@next/eslint-plugin-next": ^15.2.0
        "@tanstack/eslint-plugin-query": ^5.66.1
        "@turbo/gen": ^2.4.4
        "@typescript-eslint/eslint-plugin": ^8.26.0
        "@typescript-eslint/parser": ^8.25.0
        changelogen: ^0.6.0
        eslint: ^9.21.0
        eslint-config-prettier: ^10.0.2
        eslint-plugin-react: ^7.37.4
        eslint-plugin-react-hooks: ^5.2.0
        eslint-plugin-turbo: ^2.4.4
        globals: ^16.0.0
        husky: ^9.1.7
        lint-staged: ^15.3.0
        prettier: ^3.5.3
        prettier-plugin-tailwindcss: ^0.6.10
        turbo: ^2.4.4
        tsx: ^4.19.2
        typescript: ^5.8.2
        typescript-eslint: ^8.25.0

    vitest:
        vitest: ^3.0.5
        vite-tsconfig-paths: 5.1.4
