disallowWorkspaceCycles: true
preferFrozenLockfile: true

packages:
  - apps/*
  - packages/*
  - tooling/*

overrides:
  "next>safe-buffer": "npm:@socketregistry/safe-buffer@1.0.7"

catalogs:
  ## Direct dependencies
  web:
    "@tanstack/react-query": ^5.76.0
    babel-plugin-react-compiler: ^19.1.0-rc.1
    next: ^15.3.2
    next-themes: ^0.4.6
    next-intl: ^4.1.0
    posthog-js: ^1.240.6
    react: ^19.1.0
    react-dom: ^19.1.0

  api:
    "@hono/zod-validator": ^0.5.0
    "@openauthjs/openauth": ^0.4.3
    db0: ^0.3.2
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.43.1
    drizzle-zod: ^0.7.1
    hono: ^4.7.9
    postgres: ^3.4.5
    srvx: ^0.6.0
    unstorage: ^1.16.0

  utils:
    "@std/text": "jsr:^1.0.13"
    confbox: ^0.2.2
    defu: ^6.1.4
    esbuild: ^0.25.4
    neverthrow: ^8.2.0
    ofetch: ^1.4.1
    std-env: ^3.9.0
    tinyrainbow: ^2.0.0
    unplugin: ^2.3.3
    zod: next

  ui:
    "@icons-pack/react-simple-icons": ^12.8.0
    "@hookform/resolvers": ^5.0.1
    "@tailwindcss/postcss": ^4.1.6
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    lucide-react: ^0.507.0
    motion: ^12.10.5
    react-day-picker: ^9.6.7
    react-hook-form: ^7.56.3
    react-intersection-observer: ^9.16.0
    sonner: ^2.0.3
    tailwind-merge: ^3.3.0
    tailwindcss: ^4.1.6
    tailwindcss-animate: ^1.0.7

  radix:
    "@radix-ui/react-accordion": ^1.2.10
    "@radix-ui/react-alert-dialog": ^1.1.13
    "@radix-ui/react-aspect-ratio": ^1.1.6
    "@radix-ui/react-avatar": ^1.1.9
    "@radix-ui/react-checkbox": ^1.3.1
    "@radix-ui/react-collapsible": ^1.1.10
    "@radix-ui/react-context-menu": ^2.2.14
    "@radix-ui/react-dialog": ^1.1.13
    "@radix-ui/react-dropdown-menu": ^2.1.14
    "@radix-ui/react-hover-card": ^1.1.13
    "@radix-ui/react-label": ^2.1.6
    "@radix-ui/react-menubar": ^1.1.14
    "@radix-ui/react-navigation-menu": ^1.2.12
    "@radix-ui/react-popover": ^1.1.13
    "@radix-ui/react-progress": ^1.1.6
    "@radix-ui/react-radio-group": ^1.3.6
    "@radix-ui/react-scroll-area": ^1.2.8
    "@radix-ui/react-select": ^2.2.4
    "@radix-ui/react-separator": ^1.1.6
    "@radix-ui/react-slider": ^1.3.4
    "@radix-ui/react-slot": ^1.2.2
    "@radix-ui/react-switch": ^1.2.4
    "@radix-ui/react-tabs": ^1.1.11
    "@radix-ui/react-toast": ^1.2.13
    "@radix-ui/react-toggle": ^1.1.8
    "@radix-ui/react-toggle-group": ^1.1.9
    "@radix-ui/react-tooltip": ^1.2.6

  ##########################
  ## Tooling dependencies ##
  ##########################
  types:
    "@types/node": ^22.15.17
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3

  test:
    vitest: ^3.1.3
    vite-tsconfig-paths: ^5.1.4

  lint:
    "@biomejs/biome": 2.0.0-beta.3
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@eslint/js": ^9.26.0
    "@next/eslint-plugin-next": ^15.3.2
    "@tanstack/eslint-plugin-query": ^5.74.7
    "@typescript-eslint/eslint-plugin": ^8.32.0
    "@typescript-eslint/parser": ^8.32.0
    eslint: ^9.26.0
    eslint-config-prettier: ^10.1.5
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.3
    lint-staged: ^15.5.2
    typescript-eslint: ^8.32.0

  devtools:
    "@turbo/gen": ^2.5.3
    changelogen: ^0.6.1
    eslint-plugin-pnpm: ^0.3.1
    globals: ^16.1.0
    husky: ^9.1.7
    taze: ^19.1.0
    turbo: ^2.5.3
    tsx: ^4.19.4
    typescript: ^5.8.3
