name: Karr Server Pipeline (from Caddy)

on:
    push:
        paths:
            - apps/server/**

permissions:
    contents: read

jobs:
    build-server:
        needs: lint
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        permissions:
            contents: read
            packages: write
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Container build will fail if the Caddyfile config is invalid
            - name: Build and push Server Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/server
                  file: Dockerfile
                  push: true
                  tags: |
                      ghcr.io/finxol/karr-server:latest
                      ghcr.io/finxol/karr-server:${{ github.sha }}
