name: Karr Caddy CI

on:
    push:
        paths:
            - apps/caddy/**

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        permissions:
            contents: read
            packages: write
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Container build will fail if the Caddyfile config is invalid
            - name: Build and push Caddy Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/caddy
                  file: ./apps/caddy/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/finxol/karr-caddy:latest
                      ghcr.io/finxol/karr-caddy:${{ github.sha }}
