name: Karr CI

on:
    push:
        branches:
            - main
        tags-ignore:
            - "v*" # Ignore version tags
    pull_request:

permissions:
    contents: read

env:
    TURBO_TELEMETRY_DISABLED: 1
    # You can leverage Vercel Remote Caching with Turbo to speed up your builds
    # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    HUSKY: 0

jobs:
    checks:
        uses: ./.github/workflows/checks.yml
        secrets: inherit # Pass through secrets if needed
