name: Karr CI

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

env:
    TURBO_TELEMETRY_DISABLED: 1
    # You can leverage Vercel Remote Caching with Turbo to speed up your builds
    # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Lint project
              run: pnpm run lint

    # build-api:
    #     needs: lint
    #     runs-on: ubuntu-latest
    #     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #     permissions:
    #         contents: read
    #         packages: write
    #     steps:
    #         - name: Git Checkout
    #           uses: actions/checkout@v4

    #         - name: Log in to the Container registry
    #           uses: docker/login-action@v3
    #           with:
    #               registry: https://ghcr.io
    #               username: ${{ github.actor }}
    #               password: ${{ secrets.GITHUB_TOKEN }}

    #         - name: Build and push API Docker image
    #           uses: docker/build-push-action@v5
    #           with:
    #               context: .
    #               file: ./apps/api/Dockerfile
    #               push: true
    #               tags: |
    #                   ghcr.io/finxol/karr-api:latest
    #                   ghcr.io/finxol/karr-api:${{ github.sha }}
